### ISSUE TITLE
incorrect implementation of H_nn

### ISSUE THREAD

**Issue by hathach** [cocagne/csrp#8]
https://github.com/cocagne/csrp/blob/master/srp.c#L294

For example, when compute 
k=H(N, g) 

g must be padding to the same length of N before hashing, this cause the incorrect result to the SRP6a specs.

**Comment by cocagne** [comment]
SRP6a itself does not place any specific padding requirements on the hashing algorithm. Most likely you're referring to the hashing approach defined for the TLS implementation of SRP found in RFC5054. There is a compatibility branch of csrp that adheres to the 5054 standard and it's most likely what you're looking for. This branch has not been merged to mainline because it would break compatibility with existing csrp deployments. It should be possible to augment the implementation such that it supports both hashing approaches but no one has yet been motivated enough to implement it.

**Comment by hathach** [comment]
Sorry, it is my bad. I did check and SRP6a does not specify how the hashing should be done. However, while working with Apple Homekit Protocol specifically pairing, I figured out that  all the H_nn arguments must be padding to be able to verify proof M. I did modify the H_nn() function locally and it work greats locally. I thought I found a bug, lol !!!!

Thanks for the code
